### ISSUE TITLE
Importance of chapter name in a quartet 

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore-django#173]
What's the need for a chapter in quartet if it only allows one entry? What if there are 2, 3 or 4 chapters? How  is this entered?

**Comment by dbinetti** [comment]
This is actually a bug; there should only be a chapter for a Chorus, not a Quartet.  I'll need to fix.  In the meantime, don't add Chapters for Quartets

**Comment by russkibass** [comment]
You have to mention quartet members' chapter somewhere. like maybe in Persons? All convention programs mention individual member's chapter, so maybe adding this field to parts?

**Comment by dbinetti** [comment]
this is another good suggestion.  we'll do this.
