### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore-django#205]
There is a field in BHS membership database that is called "Title" meaning "Job title" or "position". In "Persons" there is also "Title" that may seem to mean "Mr." or anything of that sort. and I see a lot of entries like "Pastor Dean Man" or "Assistant chorus director David Mills" after the sync. Suggest removing the "Title" field unless this is reserved for some rare "birds" that want to be called "**Dr.** David Mills"

**Comment by dbinetti** [comment]
I'll update the script.  This won't take effect until the next update from the BHS

**Comment by dbinetti** [comment]
Fixed in latest update
